### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by hraban**

### CODE REVIEW

**Review by mcmillan — CHANGES_REQUESTED** [review]
needs a closing `</p>` m8

**Comment by hraban** [comment]
> A <code id="optional-tags:the-p-element">p</code> element's end tag may be omitted if the <code id="optional-tags:the-p-element-2">p</code> element is immediately followed by an <code id="optional-tags:the-address-element">address</code>, <code id="optional-tags:the-article-element">article</code>, <code id="optional-tags:the-aside-element">aside</code>, <code id="optional-tags:the-blockquote-element">blockquote</code>, <code id="optional-tags:the-details-element">details</code>, <code id="optional-tags:the-div-element">div</code>, <code id="optional-tags:the-dl-element">dl</code>, <code id="optional-tags:the-fieldset-element">fieldset</code>, <code id="optional-tags:the-figcaption-element">figcaption</code>, <code id="optional-tags:the-figure-element">figure</code>, <code id="optional-tags:the-footer-element">footer</code>, <code id="optional-tags:the-form-element">form</code>, <code id="optional-tags:the-h1,-h2,-h3,-h4,-h5,-and-h6-elements">h1</code>, <code id="optional-tags:the-h1,-h2,-h3,-h4,-h5,-and-h6-elements-2">h2</code>, <code id="optional-tags:the-h1,-h2,-h3,-h4,-h5,-and-h6-elements-3">h3</code>, <code id="optional-tags:the-h1,-h2,-h3,-h4,-h5,-and-h6-elements-4">h4</code>, <code id="optional-tags:the-h1,-h2,-h3,-h4,-h5,-and-h6-elements-5">h5</code>, <code id="optional-tags:the-h1,-h2,-h3,-h4,-h5,-and-h6-elements-6">h6</code>, <code id="optional-tags:the-header-element">header</code>, <code id="optional-tags:the-hgroup-element">hgroup</code>, <code id="optional-tags:the-hr-element">hr</code>, <code id="optional-tags:the-main-element">main</code>, <code id="optional-tags:the-menu-element">menu</code>, <code id="optional-tags:the-nav-element">nav</code>, <code id="optional-tags:the-ol-element">ol</code>, <code id="optional-tags:the-p-element-3">p</code>, <code id="optional-tags:the-pre-element">pre</code>, <code id="optional-tags:the-section-element">section</code>, <code id="optional-tags:the-table-element">table</code>, or <code id="optional-tags:the-ul-element">ul</code> element, or if there is no more content in the parent element and the parent element is an HTML element that is not an <code id="optional-tags:the-a-element">a</code>, <code id="optional-tags:the-audio-element">audio</code>, <code id="optional-tags:the-del-element">del</code>, <code id="optional-tags:the-ins-element">ins</code>, <code id="optional-tags:the-map-element">map</code>, <code id="optional-tags:the-noscript-element">noscript</code>, or <code id="optional-tags:the-video-element">video</code> element, or an autonomous custom element.

https://html.spec.whatwg.org/multipage/syntax.html#optional-tags

educate yourself.

giphy

**Comment by hraban** [comment]
thank you for your feedback sir I have processed your request for changes please sir approve the PR my family is hungry

**Comment by mcmillan** [comment]
lgtm ship it

**Comment by hraban** [comment]
+1

**Pull request merged**
